<?php

$cities_texas = array(
  'Abilene',
  'Addison',
  'Alamo',
  'Alamo Heights',
  'Allen',
  'Alpine',
  'Alvarado',
  'Alvin',
  'Amarillo',
  'Andrews',
  'Angleton',
  'Annetta',
  'Argyle',
  'Arlington',
  'Austin',
  'Azle',
  'Balch Springs',
  'Bartonville',
  'Bastrop',
  'Bay City',
  'Baytown',
  'Beaumont',
  'Bedford',
  'Bellaire',
  'Belton',
  'Benbrook',
  'Big Spring',
  'Boerne',
  'Brenham',
  'Bridge City',
  'Brownfield',
  'Brownsville',
  'Brownwood',
  'Bryan',
  'Buda',
  'Bulverde',
  'Bunker Hill Village',
  'Burkburnett',
  'Burleson',
  'Burnet',
  'Canyon',
  'Carrollton',
  'Carthage',
  'Cedar Hill',
  'Cedar Park',
  'Cleburne',
  'Clute',
  'College Station',
  'Colleyville',
  'Columbus',
  'Conroe',
  'Converse',
  'Coppell',
  'Copperas Cove',
  'Corinth',
  'Corpus Christi',
  'Corsicana',
  'Crockett',
  'Crowley',
  'Dallas',
  'DeSoto',
  'Deer Park',
  'Del Rio',
  'Denison',
  'Denton',
  'Dickinson',
  'Donna',
  'Double Oak',
  'Dumas',
  'Duncanville',
  'Eagle Pass',
  'Edinburg',
  'El Campo',
  'El Paso',
  'Ennis',
  'Euless',
  'Fairview',
  'Farmers Branch',
  'Flatonia',
  'Flower Mound',
  'Fort Stockton',
  'Fort Worth',
  'Fredericksburg',
  'Freeport',
  'Friendswood',
  'Frisco',
  'Gainesville',
  'Galveston',
  'Garland',
  'Gatesville',
  'Georgetown',
  'Gonzales',
  'Granbury',
  'Granite Shoals',
  'Grapevine',
  'Greenville',
  'Haltom City',
  'Hamilton',
  'Harker Heights',
  'Harlingen',
  'Hearne',
  'Henderson',
  'Hewitt',
  'Highland Park',
  'Highland Village',
  'Hill Country Village',
  'Hilshire Village',
  'Houston',
  'Humble',
  'Hunters Creek Village',
  'Huntsville',
  'Hurst',
  'Irving',
  'Jacksonville',
  'Jasper',
  'Jersey Village',
  'Katy',
  'Keller',
  'Kemah',
  'Kerrville',
  'Killeen',
  'Kingsville',
  'Krum',
  'Kyle',
  'La Grange',
  'La Porte',
  'Lacy-Lakeview',
  'Lago Vista',
  'Lake Jackson',
  'Lakeway',
  'Lamesa',
  'Lampasas',
  'Lancaster',
  'Laredo',
  'League City',
  'Leander',
  'Leon Valley',
  'Levelland',
  'Lewisville',
  'Littlefield',
  'Live Oak',
  'Livingston',
  'Lockhart',
  'Longview',
  'Lowry Crossing',
  'Lubbock',
  'Lucas',
  'Lufkin',
  'Mansfield',
  'Manvel',
  'Marble Falls',
  'Marshall',
  'McAllen',
  'McKinney',
  'Mesquite',
  'Midland',
  'Midlothian',
  'Mission',
  'Missouri City',
  'Mount Pleasant',
  'Nacogdoches',
  'Nassau Bay',
  'New Braunfels',
  'Newark',
  'Niederwald',
  'North Richland Hills',
  'Oak Ridge North',
  'Odessa',
  'Orange',
  'Overton',
  'Palacios',
  'Palestine',
  'Pampa',
  'Pantego',
  'Pasadena',
  'Pearland',
  'Perryton',
  'Pflugerville',
  'Plainview',
  'Plano',
  'Port Aransas',
  'Port Arthur',
  'Port Lavaca',
  'Portland',
  'Prosper',
  'Quintana',
  'Red Oak',
  'Richardson',
  'Richland Hills',
  'Rio Grande City',
  'River Oaks',
  'Rockport',
  'Rockwall',
  'Rosenberg',
  'Round Rock',
  'Rowlett',
  'Royse City',
  'Rusk',
  'Sachse',
  'Saginaw',
  'San Angelo',
  'San Antonio',
  'San Benito',
  'San Marcos',
  'San Saba',
  'Santa Fe',
  'Schertz',
  'Seabrook',
  'Sealy',
  'Seguin',
  'Selma',
  'Seymour',
  'Shady Shores',
  'Shenandoah',
  'Sherman',
  'Smithville',
  'Snyder',
  'Socorro',
  'Sonora',
  'Southlake',
  'Southside Place',
  'Spring Valley',
  'Stafford',
  'Stephenville',
  'Sugar Land',
  'Sulphur Springs',
  'Sunnyvale',
  'Sweeny',
  'Tahoka',
  'Taylor',
  'Temple',
  'Terrell',
  'Texarkana',
  'Texas City',
  'The Colony',
  'The Hills',
  'Tomball',
  'Trophy Club',
  'Tyler',
  'Universal City',
  'University Park',
  'Victoria',
  'Waco',
  'Watauga',
  'Waxahachie',
  'Weatherford',
  'Webster',
  'Weslaco',
  'West Lake Hills',
  'West Orange',
  'West University Place',
  'Westlake',
  'Weston',
  'Westover Hills',
  'Wharton',
  'White Oak',
  'White Settlement',
  'Wichita Falls',
  'Willow Park',
  'Wimberley',
  'Windcrest',
  'Woodway',
  'Wylie',
  'Yoakum'
);
